version: "2"
services:
    api:
        build:
          context: ./php
        ports: 
            - "80:80"
        restart: always
        volumes:
            - ./source:/var/www/html/
        links:
            - mariadb
        networks:
            - default
    mariadb:
        image: mariadb
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: myDB
            MYSQL_USER: webuser
            MYSQL_PASSWORD: 123456
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - phpInDocker:/var/lib/mysql
        networks:
            - default
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links: 
            - mariadb:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: webuser
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
volumes:
    phpInDocker: